# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ElasticPoolPerDatabaseSettings(Model):
    """Per database settings of an elastic pool.

    :param min_dtu: The minimum DTU all databases are guaranteed.
    :type min_dtu: int
    :param max_dtu: The maximum DTU any one database can consume.
    :type max_dtu: int
    :param min_vcores: The minimum vCores all databases are guaranteed.
    :type min_vcores: float
    :param max_vcores: The maximum vCores any one database can consume.
    :type max_vcores: float
    """

    _attribute_map = {
        'min_dtu': {'key': 'minDtu', 'type': 'int'},
        'max_dtu': {'key': 'maxDtu', 'type': 'int'},
        'min_vcores': {'key': 'minVCores', 'type': 'float'},
        'max_vcores': {'key': 'maxVCores', 'type': 'float'},
    }

    def __init__(self, min_dtu=None, max_dtu=None, min_vcores=None, max_vcores=None):
        super(ElasticPoolPerDatabaseSettings, self).__init__()
        self.min_dtu = min_dtu
        self.max_dtu = max_dtu
        self.min_vcores = min_vcores
        self.max_vcores = max_vcores
